[green_agent]
agentbeats_id = "019c0fc6-bf81-71c3-a566-1fad5a8fceec"
env = { EVALUATOR_API_KEY = "${EVALUATOR_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "agent"
env = { AGENT_API_KEY = "${AGENT_API_KEY}" }

[config]
trials = 1
