[green_agent]
agentbeats_id = "019c0fc6-bf81-71c3-a566-1fad5a8fceec"
env = { EVALUATOR_API_KEY = "${EVALUATOR_API_KEY}", EVALUATOR_URL = "${EVALUATOR_URL}", EVALUATOR_PROVIDER = "${EVALUATOR_PROVIDER}", EVALUATOR_MODEL = "${EVALUATOR_MODEL}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "TO_BE_UPDATED"
name = "agent"
env = { AGENT_API_KEY = "${AGENT_API_KEY}", AGENT_URL = "${AGENT_URL}", AGENT_PROVIDER = "${AGENT_PROVIDER}", AGENT_MODEL = "${AGENT_MODEL}" }

[config]
trials = 2
