[green_agent]
agentbeats_id = "019c0fc6-bf81-71c3-a566-1fad5a8fceec"
env = { EVALUATOR_API_KEY = "${EVALUATOR_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019c100a-630f-71d0-aeff-cb5811bf6de4"
name = "agent"
env = { AGENT_API_KEY = "${AGENT_API_KEY}", AGENT_URL = "${AGENT_URL}", AGENT_PROVIDER = "${AGENT_PROVIDER}", AGENT_MODEL = "${AGENT_MODEL}" }

[config]
trials = 1
